#!/usr/bin/env python3
"""Build both supported dedicated guests and encode deterministic built-in images.

No runtime download or consumer reexec. Regenerate source first with generate_runtime.py.
"""
import argparse
import gzip
import base64
import hashlib
import json
import os
import platform
import zlib
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--work-dir', type=Path, required=True)
    args = parser.parse_args()
    args.work_dir.mkdir(parents=True, exist_ok=True)
    records = {}
    for system, arch in [('darwin','arm64'), ('linux','amd64')]:
        binary = args.work_dir.resolve()/f'guest-{system}-{arch}'
        env=dict(os.environ, GOTOOLCHAIN='go1.26.8', CGO_ENABLED='0', GOOS=system, GOARCH=arch, GOENV='off', GOWORK='off', GOFLAGS='', GOEXPERIMENT='', GOAMD64='v1', GOARM64='v8.0')
        subprocess.run(['go','build','-p','1','-trimpath','-buildvcs=false','-o',str(binary),'./cmd/mariamem-guest'],cwd=ROOT,env=env,check=True)
        data=binary.read_bytes();sha=hashlib.sha256(data).hexdigest();compressed=gzip.compress(data,mtime=0)
        # Keep the complete module below Go's 500 MiB uncompressed zip limit.
        # Only obsolete generated image fragments may be removed.
        for old in (ROOT/'internal/builtinruntime').glob(f'data*_{system}_{arch}.go'):
            if not old.read_text().startswith('// Code generated by scripts/embed_generated_runtime.py; DO NOT EDIT.'):
                raise ValueError('refusing hand-written image source')
            old.unlink()
        dest=ROOT/f'internal/builtinruntime/image_{system}_{arch}.go'
        text='// Code generated by scripts/embed_generated_runtime.py; DO NOT EDIT.\npackage builtinruntime\nfunc image() (string,string,error) { return "'+base64.b64encode(compressed).decode()+'", "'+sha+'", nil }\n'
        dest.write_text(text)
        records[f'{system}-{arch}']={'sha256':sha,'binary_bytes':len(data),'compressed_bytes':len(compressed),'source_sha256':hashlib.sha256(text.encode()).hexdigest()}
    (ROOT/'internal/builtinruntime/provenance.json').write_text(json.dumps({'guest_sha256':json.loads((ROOT/'release/generated-go-inputs.json').read_text())['guest_sha256'],'generated_provenance_sha256':hashlib.sha256((ROOT/'internal/generatedgo/provenance.json').read_bytes()).hexdigest(),'entry_sha256':hashlib.sha256((ROOT/'cmd/mariamem-guest/main.go').read_bytes()).hexdigest(),'go':'go1.26.8','python':platform.python_version(),'zlib':zlib.ZLIB_VERSION,'go_environment':{'GOENV':'off','GOWORK':'off','GOFLAGS':'','GOEXPERIMENT':'','GOAMD64':'v1','GOARM64':'v8.0'},'build_flags':['-p','1','-trimpath','-buildvcs=false','CGO_ENABLED=0'],'images':records},indent=2)+'\n')


if __name__=='__main__':main()
